{% set name = "bqscales" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0e52fb8aac2521b7c09e90421534c9de654d44e2e97baacc3dd2a3a1711a489

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging
    - jupyterlab >=4,<5
  run:
    - python >=3.6
    - ipywidgets >=8.0.1,<9
    - numpy

test:
  imports:
    - bqscales
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/bqscales/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/bqscales/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/bqscales/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\bqscales\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\bqscales\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\bqscales\\package.json (exit 1)          # [win]

about:
  home: https://github.com/bqplot/bqscales
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Grammar of Graphics Scales for bqplot and other Jupyter Widgets libraries
  dev_url: https://github.com/bqplot/bqscales

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - ibdafna
    - kaiayoung
    - ChakriCherukuri
    - martinRenou
